config/routes.rb
Rails.application.routes.draw do
  # post 'admin#update_status'
  post 'admin/update_status', to: 'admin#update_status'
  get 'admin/index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/dashboard'
  resources :messages
  get 'home/index'
  root 'home#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
  after_initialize :defaults
  belongs_to :user
  validates :message, presence: true
  validates :number, presence: true

  def defaults
    self.status = "Pending" if self.status.nil?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
    validates :email, presence: true
    validates :passcode, presence: true
    validates :phone_number, presence: true    

    def initialize(args={})
      super
      self.passcode = args[:passcode]
      if self.passcode == "ADMIN"
        self.admin = true
      end
    end


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user_status
  def index
    # @messages = Message.all(:order => "created_at DESC")
    @messages = Message.order('created_at DESC')
  end

  def update_status
    message_id=params[:message_id]
    message_status = params[:message_status]
    message = Message.find(message_id)
    message.update_attribute(:status, message_status)
    if message.status == "sent"
      # Get twilio-ruby from twilio.com/docs/ruby/install
      # require 'rubygems'          # This line not needed for ruby > 1.8
      require 'twilio-ruby'

      # Get your Account Sid and Auth Token from twilio.com/user/account
      account_sid = 'AC4bea599df32efae66e6a1bb2121b54c5'
      auth_token = 'baeb6f34b5c039732dc88b96609d9080'
      @client = Twilio::REST::Client.new account_sid, auth_token

      api_message = @client.account.messages.create(:body => "#{current_user.email} says #{message.message}",
          :to => "#{message.number}",
          :from => "+19283251127")
      # puts message.to
      @post_status= api_message.status
      message.status = @post_status
      flash[:notice] = "Message status: #{message_status}"


    end
    # message.update_attribute(:status, post_status)
    redirect_to admin_index_path
  end


  private
  def check_user_status
    if current_user.admin == false
      redirect_to new_user_session_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to users_dashboard_path
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_message, only: [:show, :destroy]
  def index
    @messages = Message.where(user_id: current_user)
    # @messages = Message.all
    # @messages = Message.find_by_user_id
    # redirect_to users_dashboard_path
  end

  def show
    @message = Message.find(params[:id])
  end


  def new
    # @message = Message.new
    @message = current_user.messages.build
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      redirect_to @message
    else
      render 'new'
    end
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    if @message.update(message_params)
      redirect_to @message
    else
      render 'edit'
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to message_path
  end

  def delete
  end


  private
  def find_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:message, :number)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :passcode,:phone_number)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :passcode, :phone_number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def dashboard
  end
  private
  def user_params
    params.require()
    params.require(:user).permit(:email, :password, :password_confirmation, :passcode, :phone_number)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<table class="table table-hover">
  <th>
    Message
  </th>
  <th>
  Number
  </th>
  <th>
    Change Status
  </th>

  <th>
    Final Status
  </th>
  <% @messages.each do |message| %>
  <tr>
    <td><%= message.message %></td>
    <td>  <%= message.number %></td>
    <!-- <td>  <%= message.status %></td> -->
    <td>
      <%= form_tag(controller: "admin", action: "update_status", method: "post") do %>
        <select name="message_status">
        <option value="">Please select</option>
        <option value="pending" selected="selected">Pending</option>
        <option value="sent">Sent</option>
        <option value="rejected">Rejected</option>
        </select>
        <input type="submit" class="btn btn-info" value="Update">
        <input type="hidden" name="message_id" value="<%= message.id %>" >
      <% end %>
    </td>
    <td>
<%= message.status %>
    </td>

  </tr>
  <% end %>
</table>

<%= link_to 'New Message', new_message_path %>

app/views/home/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
				<h2>
					Hello, world!
				</h2>
				<p>
					Welcome to Cool Messages.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="users/sign_up">Sign Up</a>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Cool-Message</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home <span class="sr-only">(current)</span></a></li>
        <% if user_signed_in? %>
                <li><%= link_to 'New Message', new_message_path %></li>
                <li><%= link_to 'All Message', messages_path %></li>
                <% if current_user.admin == true %>
                    <li><%= link_to 'Admin Dashboard', admin_index_path %></li>
                <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to 'Account', edit_user_registration_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>

        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoolMessage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= render "layouts/navbar" %>
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>

<%= yield %>
</div>
</body>
</html>

app/views/messages/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Send new message</h4>
  </div>
  <div class="panel-body">
    <%= simple_form_for @message do |f| %>
      <div class="form-group">
        <%= f.label :message %>
        <%= f.text_field :message, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :number %><br />
        <%= f.text_field :number, class: "form-control" %>
      </div>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<table class="table table-hover">
  <th>
    Message
  </th>
  <th>
  Number
  </th>
  <th>
    Status
  </th>
  <% @messages.each do |message| %>
  <tr>
    <td><%= message.message %></td>
    <td>  <%= message.number %></td>
    <td>  <%= message.status %></td>

  </tr>
  <% end %>
</table>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<% if @message.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@message.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
    <% @message.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= render 'form' %>

app/views/messages/show.html.erb
<h2>Message</h2>
<p>
  <%= @message.message %> <br>
</p>

<h4>Number</h4>
<p>
  <%= @message.number %>
</p>
<h4>Status</h4>
<p>
  <%= @message.status %>
</p>

<%= link_to 'Back to messages', messages_path %>

app/views/users/dashboard.html.erb
<p><h2>Welcome </h2> <h4> <%= current_user.email %></h4></p>

You can <br>
<ul>
  <li><%= link_to 'View Messages & Status', messages_path %></li>
  <li><%= link_to 'Send New Message', new_message_path %></li>
</ul>